# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_PENSANDO) += elba-asic.dtb \
			       elba-asic-psci.dtb \
			       elba-secure.dtb \
			       elba-asic-psci-flash128.dtb \
			       elba-asic-flash128.dtb
dtb-$(CONFIG_ARCH_PENSANDO_GIGLIO_SOC) += giglio-asic.dtb \
					  giglio-asic-psci.dtb \
					  giglio-asic-psci-flash128.dtb \
					  giglio-asic-flash128.dtb \
					  giglio-secure.dtb giglio-deschutes-flash128.dtb
dtb-$(CONFIG_ARCH_PENSANDO_SALINA_SOC) += salina-asic.dtb \
					  salina-a35-asic.dtb \
					  salina-haps-4core.dtb \
					  salina-haps-16core.dtb \
					  salina-a35-haps.dtb \
					  salina-asic-psci.dtb \
					  salina-secure.dtb
dtb-$(CONFIG_ARCH_SEATTLE) += amd-overdrive-rev-b0.dtb amd-overdrive-rev-b1.dtb
