/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_event_channel_alloc_unbound(enum xen_hypercall_vendor vendor,
                                               struct evtchn_alloc_unbound *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 6;
    register uint64_t reg2 __asm__("rsi") = param->dom;
    register uint64_t reg3 __asm__("r8") = param->remote_dom;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->port = reg4;
    return reg0;
}

static inline
long xen_hypercall_event_channel_bind_interdomain(enum xen_hypercall_vendor vendor,
                                                  struct evtchn_bind_interdomain *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 0;
    register uint64_t reg2 __asm__("rsi") = param->remote_dom;
    register uint64_t reg3 __asm__("r8") = param->remote_port;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->local_port = reg4;
    return reg0;
}

static inline
long xen_hypercall_event_channel_bind_virq(enum xen_hypercall_vendor vendor,
                                           struct evtchn_bind_virq *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 1;
    register uint64_t reg2 __asm__("rsi") = param->virq;
    register uint64_t reg3 __asm__("r8") = param->vcpu;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->port = reg4;
    return reg0;
}

static inline
long xen_hypercall_event_channel_bind_ipi(enum xen_hypercall_vendor vendor,
                                          struct evtchn_bind_ipi *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 7;
    register uint64_t reg2 __asm__("rsi") = param->vcpu;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    param->port = reg4;
    return reg0;
}

static inline
long xen_hypercall_event_channel_bind_pirq(enum xen_hypercall_vendor vendor,
                                           struct evtchn_bind_pirq *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 2;
    register uint64_t reg2 __asm__("rsi") = param->pirq;
    register uint64_t reg3 __asm__("r8") = param->flags;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->port = reg4;
    return reg0;
}

static inline
long xen_hypercall_event_channel_close(enum xen_hypercall_vendor vendor,
                                       struct evtchn_close *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 3;
    register uint64_t reg2 __asm__("rsi") = param->port;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_send(enum xen_hypercall_vendor vendor,
                                      struct evtchn_send *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 4;
    register uint64_t reg2 __asm__("rsi") = param->port;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_status(enum xen_hypercall_vendor vendor,
                                        struct evtchn_status *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 5;
    register uint64_t reg2 __asm__("rsi") = param->dom;
    register uint64_t reg3 __asm__("r8") = param->port;
    register uint64_t reg4 __asm__("r9");
    register uint64_t reg5 __asm__("r10");
    register uint64_t reg6 __asm__("r11");
    register uint64_t reg7 __asm__("r12");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->u._output1 = reg6;
    param->u._output2 = reg7;
    param->status = reg4;
    param->vcpu = reg5;
    return reg0;
}

static inline
long xen_hypercall_event_channel_bind_vcpu(enum xen_hypercall_vendor vendor,
                                           struct evtchn_bind_vcpu *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 8;
    register uint64_t reg2 __asm__("rsi") = param->vcpu;
    register uint64_t reg3 __asm__("r8") = param->port;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_unmask(enum xen_hypercall_vendor vendor,
                                        struct evtchn_unmask *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 9;
    register uint64_t reg2 __asm__("rsi") = param->port;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_reset(enum xen_hypercall_vendor vendor,
                                       struct evtchn_reset *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 10;
    register uint64_t reg2 __asm__("rsi") = param->dom;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_init_control(enum xen_hypercall_vendor vendor,
                                              struct evtchn_init_control *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 11;
    register uint64_t reg2 __asm__("rsi") = param->control_gfn;
    register uint64_t reg3 __asm__("r8") = param->offset;
    register uint64_t reg4 __asm__("r9") = param->vcpu;
    register uint64_t reg5 __asm__("r10");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg5), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg5), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                    : "memory");

    param->link_bits = reg5;
    return reg0;
}

static inline
long xen_hypercall_event_channel_expand_array(enum xen_hypercall_vendor vendor,
                                              struct evtchn_expand_array *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 12;
    register uint64_t reg2 __asm__("rsi") = param->array_gfn;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_event_channel_set_priority(enum xen_hypercall_vendor vendor,
                                              struct evtchn_set_priority *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_event_channel_op;
    register uint64_t reg1 __asm__("rdi") = 13;
    register uint64_t reg2 __asm__("rsi") = param->port;
    register uint64_t reg3 __asm__("r8") = param->priority;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

