/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_grant_table_map_grant_ref(enum xen_hypercall_vendor vendor,
                                             struct gnttab_map_grant_ref *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_grant_table_op;
    register uint64_t reg1 __asm__("rdi") = 0;
    register uint64_t reg2 __asm__("rsi") = param->dom;
    register uint64_t reg3 __asm__("r8") = param->host_addr;
    register uint64_t reg4 __asm__("r9") = param->flags;
    register uint64_t reg5 __asm__("r10") = param->ref;
    register uint64_t reg6 __asm__("r11");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg6), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4), "r"(reg5)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg6), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4), "r"(reg5)
                                    : "memory");

    param->handle = reg6;
    return reg0;
}

static inline
long xen_hypercall_grant_table_unmap_grant_ref(enum xen_hypercall_vendor vendor,
                                               struct gnttab_unmap_grant_ref *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_grant_table_op;
    register uint64_t reg1 __asm__("rdi") = 1;
    register uint64_t reg3 __asm__("r8") = param->host_addr;
    register uint64_t reg6 __asm__("r11") = param->handle;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg3), "r"(reg6)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg3), "r"(reg6)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_grant_table_query_size(enum xen_hypercall_vendor vendor,
                                          struct gnttab_query_size *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_grant_table_op;
    register uint64_t reg1 __asm__("rdi") = 6;
    register uint64_t reg2 __asm__("rsi");
    register uint64_t reg3 __asm__("r8");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg2), "=r"(reg3), "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg2), "=r"(reg3), "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    param->max_nr_frames = reg3;
    param->nr_frames = reg2;
    return reg0;
}

static inline
long xen_hypercall_grant_table_set_version(enum xen_hypercall_vendor vendor,
                                           struct gnttab_set_version *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_grant_table_op;
    register uint64_t reg1 __asm__("rdi") = 8;
    register uint64_t reg2 __asm__("rsi") = param->version;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_grant_table_get_version(enum xen_hypercall_vendor vendor,
                                           struct gnttab_get_version *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_grant_table_op;
    register uint64_t reg1 __asm__("rdi") = 10;
    register uint64_t reg2 __asm__("rsi");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg2), "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg2), "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    param->version = reg2;
    return reg0;
}

