/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_hvm_set_param(enum xen_hypercall_vendor vendor,
                                 struct xen_hvm_param *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_hvm_op;
    register uint64_t reg1 __asm__("rdi") = 0;
    register uint64_t reg2 __asm__("rsi") = param->domid;
    register uint64_t reg3 __asm__("r8") = param->index;
    register uint64_t reg4 __asm__("r9") = param->value;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_hvm_get_param(enum xen_hypercall_vendor vendor,
                                 struct xen_hvm_param *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_hvm_op;
    register uint64_t reg1 __asm__("rdi") = 1;
    register uint64_t reg2 __asm__("rsi") = param->domid;
    register uint64_t reg3 __asm__("r8") = param->index;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->value = reg4;
    return reg0;
}

static inline
long xen_hypercall_hvm_flush_tlbs(enum xen_hypercall_vendor vendor)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_hvm_op;
    register uint64_t reg1 __asm__("rdi") = 5;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_hvm_get_mem_type(enum xen_hypercall_vendor vendor,
                                    struct xen_hvm_get_mem_type *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_hvm_op;
    register uint64_t reg1 __asm__("rdi") = 15;
    register uint64_t reg2 __asm__("rsi") = param->domid;
    register uint64_t reg3 __asm__("r8") = param->pfn;
    register uint64_t reg4 __asm__("r9");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg4), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg4), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    param->mem_type = reg4;
    return reg0;
}

static inline
long xen_hypercall_hvm_set_evtchn_upcall_vector(enum xen_hypercall_vendor vendor,
                                                struct xen_hvm_evtchn_upcall_vector *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_hvm_op;
    register uint64_t reg1 __asm__("rdi") = 23;
    register uint64_t reg2 __asm__("rsi") = param->vcpu;
    register uint64_t reg3 __asm__("r8") = param->vector;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

