/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_memory_add_to_physmap(enum xen_hypercall_vendor vendor,
                                         struct xen_add_to_physmap *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_memory_op;
    register uint64_t reg1 __asm__("rdi") = 7;
    register uint64_t reg2 __asm__("rsi") = param->size;
    register uint64_t reg3 __asm__("r8") = param->space;
    register uint64_t reg4 __asm__("r9") = param->idx;
    register uint64_t reg5 __asm__("r10") = param->gpfn;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4), "r"(reg5)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4), "r"(reg5)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_memory_remove_from_physmap(enum xen_hypercall_vendor vendor,
                                              struct xen_remove_from_physmap *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_memory_op;
    register uint64_t reg1 __asm__("rdi") = 15;
    register uint64_t reg5 __asm__("r10") = param->gpfn;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg5)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg5)
                                    : "memory");

    return reg0;
}
