/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_sched_yield(enum xen_hypercall_vendor vendor)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 0;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_block(enum xen_hypercall_vendor vendor)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 1;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_shutdown(enum xen_hypercall_vendor vendor,
                                  struct sched_shutdown *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 2;
    register uint64_t reg2 __asm__("rsi") = param->reason;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_poll(enum xen_hypercall_vendor vendor,
                              uint64_t timeout,
                              evtchn_port_t port)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 3;
    register uint64_t reg2 __asm__("rsi") = timeout;
    register uint64_t reg3 __asm__("r8") = port;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_shutdown_code(enum xen_hypercall_vendor vendor,
                                       struct sched_shutdown *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 5;
    register uint64_t reg2 __asm__("rsi") = param->reason;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_watchdog(enum xen_hypercall_vendor vendor,
                                  struct sched_watchdog *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 6;
    register uint64_t reg2 __asm__("rsi") = param->id;
    register uint64_t reg3 __asm__("r8") = param->timeout;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_sched_pin_override(enum xen_hypercall_vendor vendor,
                                      struct sched_pin_override *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_sched_op;
    register uint64_t reg1 __asm__("rdi") = 7;
    register uint64_t reg2 __asm__("rsi") = param->pcpu;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

