/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_vcpu_initialise(enum xen_hypercall_vendor vendor,
                                   uint32_t vcpuid,
                                   uint64_t context_gfn)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 0;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = context_gfn;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_up(enum xen_hypercall_vendor vendor,
                           uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 1;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_down(enum xen_hypercall_vendor vendor,
                             uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 2;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_is_up(enum xen_hypercall_vendor vendor,
                              uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 3;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_get_runstate_info(enum xen_hypercall_vendor vendor,
                                          struct vcpu_runstate_info *param,
                                          uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 4;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8");
    register uint64_t reg4 __asm__("r9");
    register uint64_t reg5 __asm__("r10");
    register uint64_t reg6 __asm__("r11");
    register uint64_t reg7 __asm__("r12");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7), "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg2), "=r"(reg3), "=r"(reg4), "=r"(reg5), "=r"(reg6), "=r"(reg7), "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    param->state = reg2;
    param->state_entry_time = reg3;
    param->time[0] = reg4;
    param->time[1] = reg5;
    param->time[2] = reg6;
    param->time[3] = reg7;
    return reg0;
}

static inline
long xen_hypercall_vcpu_register_runstate_phys_area(enum xen_hypercall_vendor vendor,
                                                    struct vcpu_register_time_memory_area *param,
                                                    uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 14;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->addr.p;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_set_periodic_timer(enum xen_hypercall_vendor vendor,
                                           struct vcpu_set_periodic_timer *param,
                                           uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 6;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->period_ns;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_stop_periodic_timer(enum xen_hypercall_vendor vendor,
                                            uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 7;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_set_singleshot_timer(enum xen_hypercall_vendor vendor,
                                             struct vcpu_set_singleshot_timer *param,
                                             uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 8;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->timeout_abs_ns;
    register uint64_t reg4 __asm__("r9") = param->flags;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_stop_singleshot_timer(enum xen_hypercall_vendor vendor,
                                              uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 9;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_register_vcpu_info(enum xen_hypercall_vendor vendor,
                                           struct vcpu_register_vcpu_info *param,
                                           uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 10;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->mfn;
    register uint64_t reg4 __asm__("r9") = param->offset;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3), "r"(reg4)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_send_nmi(enum xen_hypercall_vendor vendor,
                                 uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 11;
    register uint64_t reg2 __asm__("rsi") = vcpuid;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_get_physid(enum xen_hypercall_vendor vendor,
                                   struct vcpu_get_physid *param,
                                   uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 12;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->phys_id;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_vcpu_register_vcpu_time_phys_area(enum xen_hypercall_vendor vendor,
                                                     struct vcpu_register_time_memory_area *param,
                                                     uint32_t vcpuid)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_vcpu_op;
    register uint64_t reg1 __asm__("rdi") = 15;
    register uint64_t reg2 __asm__("rsi") = vcpuid;
    register uint64_t reg3 __asm__("r8") = param->addr.p;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1), "r"(reg2), "r"(reg3)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1), "r"(reg2), "r"(reg3)
                                    : "memory");

    return reg0;
}

