/* SPDX-License-Identifier: MIT */
/* AUTOGENERATED. DO NOT MODIFY */

static inline
long xen_hypercall_version_version(enum xen_hypercall_vendor vendor)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_xen_version;
    register uint64_t reg1 __asm__("rdi") = 0;

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "+r"(reg0)
                                   : "r"(reg1)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "+r"(reg0)
                                    : "r"(reg1)
                                    : "memory");

    return reg0;
}

static inline
long xen_hypercall_version_get_features(enum xen_hypercall_vendor vendor,
                                        struct xen_feature_info *param)
{
    register long reg0 __asm__("rax") = __HYPERVISOR_FASTABI_MASK | __HYPERVISOR_xen_version;
    register uint64_t reg1 __asm__("rdi") = 6;
    register uint64_t reg2 __asm__("rsi") = param->submap_idx;
    register uint64_t reg3 __asm__("r8");

    if ( vendor == Intel )
        __asm__ volatile ("vmcall" : "=r"(reg3), "+r"(reg0)
                                   : "r"(reg1), "r"(reg2)
                                   : "memory");
    else
        __asm__ volatile ("vmmcall" : "=r"(reg3), "+r"(reg0)
                                    : "r"(reg1), "r"(reg2)
                                    : "memory");

    param->submap = reg3;
    return reg0;
}

